# Application Configurations

# Spring Application
spring:
  # JPA
  jpa:
    # MySQL Connection
    datasource:
      url: jdbc:mysql://localhost:3306/spring_boot
      username: root
      password: randompassword
      driverClassName: com.mysql.jdbc.Driver
    # Other Configurations
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # Redis Connection
  redis:
    # Db Index
    database: 0
    host: localhost
    port: 6379
    timeout: 0

  # Profiles
  profiles:
    active: dev

# Web Server (Tomcat)
server:
  port: 9097
