# Application Configurations [dev]

# Spring Application
spring:
  # MySQL Connection
  datasource:
    url: jdbc:mysql://mysql:3306/spring_boot
    username: root
    password: 123123
    driverClassName: com.mysql.jdbc.Driver
  # Redis Connection
  redis:
    # Db Index
    host: redis
    port: 6379
    timeout: 0

# Logging
logging:
  path:
    dir: "/var/log/spring-boot"
    archive: "archive"
  file: "stdout"

# Web Server (Tomcat)
server:
  port: 8080
