# Application Configurations

# Spring Application
spring:
  # MySQL Connection
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot
    username: root
    password: randompassword
    driverClassName: com.mysql.jdbc.Driver
  # JPA
  jpa:
    properties.hibernate:
      hbm2ddl:
        auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  # Redis Connection
  redis:
    # Db Index
    host: localhost
    port: 6379
    timeout: 0

  # Profiles
  profiles.active: dev

# Logging
logging:
  path:
    dir: "logs"
    archive: "archive"
  # Filename of logs:
  # ${loggine.file}.log
  file: "app"
  level:
    org.springframework.web: INFO
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"

# Web Server (Tomcat)
server:
  port: 9097
